Feature: Jump to beginning and end of tag
felipeochoa/rjsx-mode pull request #91
Opened 2018-10-20 17:36 UTC by larebsyed

**Description**
- In rjsx mode there is no way to jump to closing tag or beginning tag
- This PR adds three more interactive functions rjsx-jump-to-closing-tag, rjsx-jump-to-opening-tag and rjsx-jump-tag
- With rjsx-jump-tag we can alternate between beginning and end tag
- rjsx-jump-tag is bound to C-c C-g by default

2018-10-26 07:36 UTC, larebsyed commented
@felipeochoa Please review. Thanks

2018-11-02 12:57 UTC, larebsyed commented
@felipeochoa  any update?

2018-11-13 16:45 UTC, felipeochoa requested changes

2018-11-13 16:45 UTC, felipeochoa commented on rjsx-mode.el
> +     (t
If `tag` is a self-closing tag, what happens here?

2018-11-13 16:45 UTC, felipeochoa commented on rjsx-mode.el
> +     ))))
Can you keep closing parentheses on the preceding line here and elsewhere?

2018-11-13 16:45 UTC, felipeochoa commented on rjsx-mode.el
> +  "Goto closing tag of focused tab body"
Fix the docstring here
```suggestion
  "Go to closing tag of tag at point."
```

2018-11-13 16:45 UTC, felipeochoa commented on rjsx-mode.el
> +  "Goto opening tag of focused tab body"
Fix doc string
```suggestion
  "Go to opening tag of tag at point."
```

2018-11-13 16:45 UTC, felipeochoa commented on rjsx-mode.el
> +         (closer (and tag (rjsx-node-closing-tag tag))))
`closer` is unused here

2018-11-13 16:45 UTC, felipeochoa commented on rjsx-mode.el
> +     ((eq (line-number-at-pos (js2-node-abs-pos tag)) (line-number-at-pos)) (rjsx-jump-closing-tag))
This test will fail if you have a multi-line tag. I'd rather have the check just be `(= (point) (js2-node-abs-pos tag))`. If you're not at the very beginning of the tag, it takes you there, otherwise it takes you to the closing tag.

2018-11-13 16:45 UTC, felipeochoa commented on rjsx-mode.el
> +(define-key rjsx-mode-map (kbd "C-c C-g") 'rjsx-jump-tag)
`C-g` should always be `keyboard-quit`. Maybe `C-c C-j` would be better?

2018-11-25 09:14 UTC, larebsyed commented on rjsx-mode.el
> +  "Goto opening tag of focused tab body"
done

2018-11-25 09:15 UTC, larebsyed commented on rjsx-mode.el
> +     ))))
done

2018-11-25 09:17 UTC, larebsyed commented on rjsx-mode.el
> +     ((eq (line-number-at-pos (js2-node-abs-pos tag)) (line-number-at-pos)) (rjsx-jump-closing-tag))
Basically, I added this check to make sure, that we only jump to start or end tag. If we are inside a tag and not inside the tag body. I think it is better to limit the functionality to start and end lines of tag.

2018-11-25 09:17 UTC, larebsyed commented on rjsx-mode.el
> +(define-key rjsx-mode-map (kbd "C-c C-g") 'rjsx-jump-tag)
done

2018-11-25 09:18 UTC, larebsyed commented on rjsx-mode.el
> +         (closer (and tag (rjsx-node-closing-tag tag))))
removed

2018-12-01 01:33 UTC, felipeochoa commented on rjsx-mode.el
> +     ((eq (line-number-at-pos (js2-node-abs-pos tag)) (line-number-at-pos)) (rjsx-jump-closing-tag))
How would it be intrusive? If the user calls this function they clearly expect it to do something no?

2018-12-01 01:34 UTC, felipeochoa commented on rjsx-mode.el
> +     (t
Where is that happening? Wouldn't a self closing tag result in a nil error when calling `js2-node-abs-pos`?

2018-12-01 01:36 UTC, felipeochoa commented
Added a couple small comments. Otherwise we just need a few tests for this and it looks good. Thanks!!

2018-12-01 02:53 UTC, larebsyed commented on rjsx-mode.el
> +     (t
yup you are right, I have fixed this

2018-12-01 03:13 UTC, larebsyed commented on rjsx-mode.el
> +     ((eq (line-number-at-pos (js2-node-abs-pos tag)) (line-number-at-pos)) (rjsx-jump-closing-tag))
I tried doing it like you suggested, but in using '(= (point) (js2-node-abs-pos tag))'. Jump only works when the cursor is at the start '<' which seems very limited. In case of multiline tags the command automatically jump to first line of tag and the jump again will jump to closing tag line. Which seems to be more usable.

2018-12-01 03:17 UTC, larebsyed commented
@felipeochoa Fixed and replied to your comments

2018-12-01 15:13 UTC, felipeochoa commented on rjsx-mode.el
> +     ((eq (line-number-at-pos (js2-node-abs-pos tag)) (line-number-at-pos)) (rjsx-jump-closing-tag))
Just tried it out -- this is great!

2018-12-01 15:14 UTC, felipeochoa commented on rjsx-mode.el
> +     ((eq (line-number-at-pos (js2-node-abs-pos tag)) (line-number-at-pos)) (rjsx-jump-closing-tag))
Just tried it -- this is great!

2018-12-01 15:14 UTC, felipeochoa approved these changes

2018-12-01 15:16 UTC, felipeochoa commented
Final thing before merging: Can you add a couple of tests? You can look in `rjsx-tests.el` at either `rjsx-rename-tag-at-point` or `rjsx--tag-at-point` for inspiration

2018-12-03 19:56 UTC, larebsyed commented
@felipeochoa Added a couple of test, please merge if you find them enough

2018-12-04 19:40 UTC, larebsyed commented
@felipeochoa Added another test for rjsx-jump-tag, I was not sure how should I test it as it uses the same funcation `rjsx-jump-opening-tag` and `rjsx-jump-closing-tag` at the back. Let me know if it is fine like this.

2018-12-06 01:58 UTC, larebsyed commented
@felipeochoa should I merge this?

2018-12-07 08:03 UTC, merged

2018-12-07 08:03 UTC, felipeochoa commented
Thank you!!

2018-12-14 09:35 UTC, littlehome-eugene commented
great, it's C-c C-j not C-c C-g by default..

2018-12-14 10:01 UTC, larebsyed commented
Edited it Thanks

2021-02-26 19:30 UTC, wminshew commented
something odd I noticed: jumping from the close tag to open tag only works if they're on different lines. Not saying it's a bug, but something that felt worth noting (jumping from open tag to close tag on same line works as expected)